version: '2'

services:

  # File storage
  web_data:
    container_name: web_data
    image         : web_data
    build:
      context : .
      dockerfile: web_data.dockerfile
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./var/www/html/:/var/www/html/

  # PHP install
  web_php:
    container_name: web_php
    image         : web_php
    build:
      context : .
      dockerfile: web_php.dockerfile
    volumes_from:
      - web_data

  # NGINX install
  web_server:
    container_name: web_server
    image         : web_server
    build:
      context : .
      dockerfile: web_server.dockerfile
    volumes_from:
      - web_data
    ports:
     - "8080:80"

  # MYSQL install
  web_db:
    container_name: web_db
    image         : web_db
    build:
      context : .
      dockerfile: web_db.dockerfile
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD  : 1
      MYSQL_ROOT_PASSWORD         : ''
      MYSQL_USER                  : arnottg
      MYSQL_PASSWORD              : pa33word
      MYSQL_DATABASE              : web_db